title: Aubret Arthur thesis
email: arthur.aubret@univ-lyon1.fr
description: >- Deep reinforcement learning of interaction's contexts for multi-agents coordination.
github_username:  Aubret
theme: jekyll-theme-cayman
